version: '3'
services:
  postgres:
    container_name: pgadmin_container
    image: postgres:latest
    environment:
      POSTGRES_DB: hub_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10021977
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: ./
#      dockerfile: Dockerfile  # Seu Dockerfile
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hub_payment
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 10021977
      access_token: ${access_token}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src/main:/app/src/main
