version: '3'
services:
  postgres:
    container_name: pgadmin_container
    image: postgres:latest
    environment:
      POSTGRES_DB: hub_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10021977
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    container_name: spring-boot-app
    image: hub_payment_0.0.4
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hub_payment
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      access_token: ${access_token}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src/main:/app/src/main

# mvn package            (Generated as new .jar)
# docker build -t [name] . (Generated as new image)

# docker-compose up      (Create new network)
# docker-compose up -d   (Recreated as new docker image)
# docker-compose down    (Delete as network)
# docker-compose stop    (Stop as network)